//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies_table
    {
        public int Movie_id { get; set; }
        public string Movie_name { get; set; }
        public int Production_Year { get; set; }
        public string Director_name { get; set; }
        public int Movie_duration_in_hours { get; set; }
    }
}
